.TH "_mastery" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mastery \- project Dev10 
created as a Dev10 project\&. Assessment: Don't wreck my house
.PP
\fBSee also\fP
.RS 4
https://github.com/see-k/dontWreckMyHouse/blob/main/docs/README.md 
.RE
.PP

