.TH "learn.reservation.domain.HostService" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.domain.HostService
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHostService\fP (\fBHostRepository\fP hostRepository)"
.br
.ti -1c
.RI "\fBHost\fP \fBfindByEmail\fP (String email)  throws DataException "
.br
.ti -1c
.RI "BigDecimal \fBgetTotal\fP (String hostEmail, List< LocalDate > dates)  throws DataException  "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "learn\&.reservation\&.domain\&.HostService\&.HostService (\fBHostRepository\fP hostRepository)"

.SH "Member Function Documentation"
.PP 
.SS "\fBHost\fP learn\&.reservation\&.domain\&.HostService\&.findByEmail (String email) throws \fBDataException\fP"

.SS "BigDecimal learn\&.reservation\&.domain\&.HostService\&.getTotal (String hostEmail, List< LocalDate > dates) throws \fBDataException\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
