.TH "learn.reservation.models.Reservation" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.models.Reservation
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (int id)"
.br
.ti -1c
.RI "LocalDate \fBgetStartDate\fP ()"
.br
.ti -1c
.RI "void \fBsetStartDate\fP (LocalDate startDate)"
.br
.ti -1c
.RI "LocalDate \fBgetEndDate\fP ()"
.br
.ti -1c
.RI "void \fBsetEndDate\fP (LocalDate endDate)"
.br
.ti -1c
.RI "int \fBgetGuestId\fP ()"
.br
.ti -1c
.RI "void \fBsetGuestId\fP (int guestId)"
.br
.ti -1c
.RI "BigDecimal \fBgetTotal\fP ()"
.br
.ti -1c
.RI "void \fBsetTotal\fP (BigDecimal total)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "LocalDate learn\&.reservation\&.models\&.Reservation\&.getEndDate ()"

.SS "int learn\&.reservation\&.models\&.Reservation\&.getGuestId ()"

.SS "int learn\&.reservation\&.models\&.Reservation\&.getId ()"

.SS "LocalDate learn\&.reservation\&.models\&.Reservation\&.getStartDate ()"

.SS "BigDecimal learn\&.reservation\&.models\&.Reservation\&.getTotal ()"

.SS "void learn\&.reservation\&.models\&.Reservation\&.setEndDate (LocalDate endDate)"

.SS "void learn\&.reservation\&.models\&.Reservation\&.setGuestId (int guestId)"

.SS "void learn\&.reservation\&.models\&.Reservation\&.setId (int id)"

.SS "void learn\&.reservation\&.models\&.Reservation\&.setStartDate (LocalDate startDate)"

.SS "void learn\&.reservation\&.models\&.Reservation\&.setTotal (BigDecimal total)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
