.TH "learn.reservation.data.HostFileRepository" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.data.HostFileRepository
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlearn\&.reservation\&.data\&.HostRepository\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHostFileRepository\fP (@Value('${dataFilePathHost}') String filePath)"
.br
.ti -1c
.RI "List< \fBHost\fP > \fBfindAll\fP ()"
.br
.ti -1c
.RI "\fBHost\fP \fBfindById\fP (String id)"
.br
.ti -1c
.RI "\fBHost\fP \fBfindByEmail\fP (String email)  throws DataException "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "learn\&.reservation\&.data\&.HostFileRepository\&.HostFileRepository (@Value('${dataFilePathHost}') String filePath)"

.SH "Member Function Documentation"
.PP 
.SS "List<\fBHost\fP> learn\&.reservation\&.data\&.HostFileRepository\&.findAll ()"

.PP
Implements \fBlearn\&.reservation\&.data\&.HostRepository\fP\&.
.SS "\fBHost\fP learn\&.reservation\&.data\&.HostFileRepository\&.findByEmail (String email) throws \fBDataException\fP"

.PP
Implements \fBlearn\&.reservation\&.data\&.HostRepository\fP\&.
.SS "\fBHost\fP learn\&.reservation\&.data\&.HostFileRepository\&.findById (String id)"

.PP
Implements \fBlearn\&.reservation\&.data\&.HostRepository\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
