.TH "learn.reservation.domain.GuestService" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.domain.GuestService
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGuestService\fP (\fBGuestRepository\fP repository)"
.br
.ti -1c
.RI "\fBGuest\fP \fBfindByGuestEmail\fP (String email)"
.br
.ti -1c
.RI "List< \fBGuest\fP > \fBfindAllGuests\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "learn\&.reservation\&.domain\&.GuestService\&.GuestService (\fBGuestRepository\fP repository)"

.SH "Member Function Documentation"
.PP 
.SS "List<\fBGuest\fP> learn\&.reservation\&.domain\&.GuestService\&.findAllGuests ()"

.SS "\fBGuest\fP learn\&.reservation\&.domain\&.GuestService\&.findByGuestEmail (String email)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
