.TH "learn.reservation.data.GuestFileRepository" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.data.GuestFileRepository
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlearn\&.reservation\&.data\&.GuestRepository\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGuestFileRepository\fP (@Value('${dataFilePathGuest}') String filePath)"
.br
.ti -1c
.RI "List< \fBGuest\fP > \fBfindAll\fP ()"
.br
.ti -1c
.RI "\fBGuest\fP \fBfindByEmail\fP (String email)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "learn\&.reservation\&.data\&.GuestFileRepository\&.GuestFileRepository (@Value('${dataFilePathGuest}') String filePath)"

.SH "Member Function Documentation"
.PP 
.SS "List<\fBGuest\fP> learn\&.reservation\&.data\&.GuestFileRepository\&.findAll ()"

.PP
Implements \fBlearn\&.reservation\&.data\&.GuestRepository\fP\&.
.SS "\fBGuest\fP learn\&.reservation\&.data\&.GuestFileRepository\&.findByEmail (String email)"

.PP
Implements \fBlearn\&.reservation\&.data\&.GuestRepository\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
