.TH "learn.reservation.models.Guest" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.models.Guest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (int id)"
.br
.ti -1c
.RI "String \fBgetFirstName\fP ()"
.br
.ti -1c
.RI "void \fBsetFirstName\fP (String firstName)"
.br
.ti -1c
.RI "String \fBgetLastName\fP ()"
.br
.ti -1c
.RI "void \fBsetLastName\fP (String lastName)"
.br
.ti -1c
.RI "String \fBgetEmail\fP ()"
.br
.ti -1c
.RI "void \fBsetEmail\fP (String email)"
.br
.ti -1c
.RI "String \fBgetPhone\fP ()"
.br
.ti -1c
.RI "void \fBsetPhone\fP (String phone)"
.br
.ti -1c
.RI "String \fBgetState\fP ()"
.br
.ti -1c
.RI "void \fBsetState\fP (String state)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "String learn\&.reservation\&.models\&.Guest\&.getEmail ()"

.SS "String learn\&.reservation\&.models\&.Guest\&.getFirstName ()"

.SS "int learn\&.reservation\&.models\&.Guest\&.getId ()"

.SS "String learn\&.reservation\&.models\&.Guest\&.getLastName ()"

.SS "String learn\&.reservation\&.models\&.Guest\&.getPhone ()"

.SS "String learn\&.reservation\&.models\&.Guest\&.getState ()"

.SS "void learn\&.reservation\&.models\&.Guest\&.setEmail (String email)"

.SS "void learn\&.reservation\&.models\&.Guest\&.setFirstName (String firstName)"

.SS "void learn\&.reservation\&.models\&.Guest\&.setId (int id)"

.SS "void learn\&.reservation\&.models\&.Guest\&.setLastName (String lastName)"

.SS "void learn\&.reservation\&.models\&.Guest\&.setPhone (String phone)"

.SS "void learn\&.reservation\&.models\&.Guest\&.setState (String state)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
