.TH "learn.reservation.ui.MainMenuOption" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.ui.MainMenuOption
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetValue\fP ()"
.br
.ti -1c
.RI "String \fBgetMessage\fP ()"
.br
.ti -1c
.RI "boolean \fBisHidden\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBMainMenuOption\fP \fBfromValue\fP (int value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEXIT\fP =(0, 'Exit', false)"
.br
.ti -1c
.RI "\fBVIEW_RESERVATIONS_FOR_HOST\fP =(1, 'View Reservations for Host', false)"
.br
.ti -1c
.RI "\fBMAKE_RESERVATION\fP =(2, 'Make a \fBReservation\fP', false)"
.br
.ti -1c
.RI "\fBEDIT_RESERVATION\fP =(3, 'Edit a \fBReservation\fP', false)"
.br
.ti -1c
.RI "\fBCANCEL_RESERVATION\fP =(4, 'Cancel a \fBReservation\fP', false)"
.br
.ti -1c
.RI "\fBVIEW_RESERVATIONS_FOR_GUEST\fP =(5, 'View Reservations for \fBGuest\fP', false)"
.br
.ti -1c
.RI "\fBVIEW_RESERVATIONS_BY_STATE\fP =(6, 'View Reservations by State', false)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static \fBMainMenuOption\fP learn\&.reservation\&.ui\&.MainMenuOption\&.fromValue (int value)\fC [static]\fP"

.SS "String learn\&.reservation\&.ui\&.MainMenuOption\&.getMessage ()"

.SS "int learn\&.reservation\&.ui\&.MainMenuOption\&.getValue ()"

.SS "boolean learn\&.reservation\&.ui\&.MainMenuOption\&.isHidden ()"

.SH "Member Data Documentation"
.PP 
.SS "learn\&.reservation\&.ui\&.MainMenuOption\&.CANCEL_RESERVATION =(4, 'Cancel a \fBReservation\fP', false)"

.SS "learn\&.reservation\&.ui\&.MainMenuOption\&.EDIT_RESERVATION =(3, 'Edit a \fBReservation\fP', false)"

.SS "learn\&.reservation\&.ui\&.MainMenuOption\&.EXIT =(0, 'Exit', false)"

.SS "learn\&.reservation\&.ui\&.MainMenuOption\&.MAKE_RESERVATION =(2, 'Make a \fBReservation\fP', false)"

.SS "learn\&.reservation\&.ui\&.MainMenuOption\&.VIEW_RESERVATIONS_BY_STATE =(6, 'View Reservations by State', false)"

.SS "learn\&.reservation\&.ui\&.MainMenuOption\&.VIEW_RESERVATIONS_FOR_GUEST =(5, 'View Reservations for \fBGuest\fP', false)"

.SS "learn\&.reservation\&.ui\&.MainMenuOption\&.VIEW_RESERVATIONS_FOR_HOST =(1, 'View Reservations for Host', false)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
