.TH "learn.reservation.data.HostRepository" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.data.HostRepository
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBlearn\&.reservation\&.data\&.HostFileRepository\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< \fBHost\fP > \fBfindAll\fP ()"
.br
.ti -1c
.RI "\fBHost\fP \fBfindById\fP (String id)"
.br
.ti -1c
.RI "\fBHost\fP \fBfindByEmail\fP (String email)  throws DataException"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "List<\fBHost\fP> learn\&.reservation\&.data\&.HostRepository\&.findAll ()"

.PP
Implemented in \fBlearn\&.reservation\&.data\&.HostFileRepository\fP\&.
.SS "\fBHost\fP learn\&.reservation\&.data\&.HostRepository\&.findByEmail (String email) throws \fBDataException\fP"

.PP
Implemented in \fBlearn\&.reservation\&.data\&.HostFileRepository\fP\&.
.SS "\fBHost\fP learn\&.reservation\&.data\&.HostRepository\&.findById (String id)"

.PP
Implemented in \fBlearn\&.reservation\&.data\&.HostFileRepository\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
