.TH "learn.reservation.ui.ConsoleIO" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.ui.ConsoleIO
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBprint\fP (String message)"
.br
.ti -1c
.RI "void \fBprintln\fP (String message)"
.br
.ti -1c
.RI "void \fBprintf\fP (String format, Object\&.\&.\&. values)"
.br
.ti -1c
.RI "String \fBreadString\fP (String prompt)"
.br
.ti -1c
.RI "String \fBreadRequiredString\fP (String prompt)"
.br
.ti -1c
.RI "double \fBreadDouble\fP (String prompt)"
.br
.ti -1c
.RI "double \fBreadDouble\fP (String prompt, double min, double max)"
.br
.ti -1c
.RI "int \fBreadInt\fP (String prompt)"
.br
.ti -1c
.RI "int \fBreadInt\fP (String prompt, int min, int max)"
.br
.ti -1c
.RI "boolean \fBreadBoolean\fP (String prompt)"
.br
.ti -1c
.RI "LocalDate \fBreadLocalDate\fP (String prompt)"
.br
.ti -1c
.RI "BigDecimal \fBreadBigDecimal\fP (String prompt)"
.br
.ti -1c
.RI "BigDecimal \fBreadBigDecimal\fP (String prompt, BigDecimal min, BigDecimal max)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void learn\&.reservation\&.ui\&.ConsoleIO\&.print (String message)"

.SS "void learn\&.reservation\&.ui\&.ConsoleIO\&.printf (String format, Object\&.\&.\&. values)"

.SS "void learn\&.reservation\&.ui\&.ConsoleIO\&.println (String message)"

.SS "BigDecimal learn\&.reservation\&.ui\&.ConsoleIO\&.readBigDecimal (String prompt)"

.SS "BigDecimal learn\&.reservation\&.ui\&.ConsoleIO\&.readBigDecimal (String prompt, BigDecimal min, BigDecimal max)"

.SS "boolean learn\&.reservation\&.ui\&.ConsoleIO\&.readBoolean (String prompt)"

.SS "double learn\&.reservation\&.ui\&.ConsoleIO\&.readDouble (String prompt)"

.SS "double learn\&.reservation\&.ui\&.ConsoleIO\&.readDouble (String prompt, double min, double max)"

.SS "int learn\&.reservation\&.ui\&.ConsoleIO\&.readInt (String prompt)"

.SS "int learn\&.reservation\&.ui\&.ConsoleIO\&.readInt (String prompt, int min, int max)"

.SS "LocalDate learn\&.reservation\&.ui\&.ConsoleIO\&.readLocalDate (String prompt)"

.SS "String learn\&.reservation\&.ui\&.ConsoleIO\&.readRequiredString (String prompt)"

.SS "String learn\&.reservation\&.ui\&.ConsoleIO\&.readString (String prompt)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
