.TH "learn.reservation.data.GuestRepository" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.data.GuestRepository
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBlearn\&.reservation\&.data\&.GuestFileRepository\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< \fBGuest\fP > \fBfindAll\fP ()"
.br
.ti -1c
.RI "\fBGuest\fP \fBfindByEmail\fP (String email)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "List<\fBGuest\fP> learn\&.reservation\&.data\&.GuestRepository\&.findAll ()"

.PP
Implemented in \fBlearn\&.reservation\&.data\&.GuestFileRepository\fP\&.
.SS "\fBGuest\fP learn\&.reservation\&.data\&.GuestRepository\&.findByEmail (String email)"

.PP
Implemented in \fBlearn\&.reservation\&.data\&.GuestFileRepository\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
