.TH "learn.reservation.data.ReservationRepositoryDouble" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.data.ReservationRepositoryDouble
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlearn\&.reservation\&.data\&.ReservationRepository\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReservationRepositoryDouble\fP ()"
.br
.ti -1c
.RI "\fBReservation\fP \fBadd\fP (\fBReservation\fP reservation, String hostId)  throws DataException "
.br
.ti -1c
.RI "List< \fBReservation\fP > \fBfindAll\fP (String hostId)"
.br
.ti -1c
.RI "\fBReservation\fP \fBupdate\fP (\fBReservation\fP reservation, String hostId)  throws DataException "
.br
.ti -1c
.RI "\fBReservation\fP \fBdelete\fP (int guestId, String hostId)  throws DataException "
.br
.ti -1c
.RI "List< \fBReservation\fP > \fBfindGuestReservations\fP (int guestId, List< \fBHost\fP > hosts)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "learn\&.reservation\&.data\&.ReservationRepositoryDouble\&.ReservationRepositoryDouble ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBReservation\fP learn\&.reservation\&.data\&.ReservationRepositoryDouble\&.add (\fBReservation\fP reservation, String hostId) throws \fBDataException\fP"

.PP
Implements \fBlearn\&.reservation\&.data\&.ReservationRepository\fP\&.
.SS "\fBReservation\fP learn\&.reservation\&.data\&.ReservationRepositoryDouble\&.delete (int guestId, String hostId) throws \fBDataException\fP"

.PP
Implements \fBlearn\&.reservation\&.data\&.ReservationRepository\fP\&.
.SS "List<\fBReservation\fP> learn\&.reservation\&.data\&.ReservationRepositoryDouble\&.findAll (String hostId)"

.PP
Implements \fBlearn\&.reservation\&.data\&.ReservationRepository\fP\&.
.SS "List<\fBReservation\fP> learn\&.reservation\&.data\&.ReservationRepositoryDouble\&.findGuestReservations (int guestId, List< \fBHost\fP > hosts)"

.PP
Implements \fBlearn\&.reservation\&.data\&.ReservationRepository\fP\&.
.SS "\fBReservation\fP learn\&.reservation\&.data\&.ReservationRepositoryDouble\&.update (\fBReservation\fP reservation, String hostId) throws \fBDataException\fP"

.PP
Implements \fBlearn\&.reservation\&.data\&.ReservationRepository\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
