.TH "learn.reservation.ui.Controller" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.ui.Controller
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBController\fP (\fBHostService\fP hostService, \fBGuestService\fP guestService, \fBReservationService\fP reservationService, \fBView\fP view)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "learn\&.reservation\&.ui\&.Controller\&.Controller (\fBHostService\fP hostService, \fBGuestService\fP guestService, \fBReservationService\fP reservationService, \fBView\fP view)"

.SH "Member Function Documentation"
.PP 
.SS "void learn\&.reservation\&.ui\&.Controller\&.run ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
