.TH "learn.reservation.models.Host" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.models.Host
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (String id)"
.br
.ti -1c
.RI "String \fBgetLastName\fP ()"
.br
.ti -1c
.RI "void \fBsetLastName\fP (String lastName)"
.br
.ti -1c
.RI "String \fBgetEmail\fP ()"
.br
.ti -1c
.RI "void \fBsetEmail\fP (String email)"
.br
.ti -1c
.RI "String \fBgetPhone\fP ()"
.br
.ti -1c
.RI "void \fBsetPhone\fP (String phone)"
.br
.ti -1c
.RI "String \fBgetAddress\fP ()"
.br
.ti -1c
.RI "void \fBsetAddress\fP (String address)"
.br
.ti -1c
.RI "String \fBgetCity\fP ()"
.br
.ti -1c
.RI "void \fBsetCity\fP (String city)"
.br
.ti -1c
.RI "String \fBgetState\fP ()"
.br
.ti -1c
.RI "void \fBsetState\fP (String state)"
.br
.ti -1c
.RI "int \fBgetPostalCode\fP ()"
.br
.ti -1c
.RI "void \fBsetPostalCode\fP (int postalCode)"
.br
.ti -1c
.RI "BigDecimal \fBgetStandardRate\fP ()"
.br
.ti -1c
.RI "void \fBsetStandardRate\fP (BigDecimal standardRate)"
.br
.ti -1c
.RI "BigDecimal \fBgetWeekendRate\fP ()"
.br
.ti -1c
.RI "void \fBsetWeekendRate\fP (BigDecimal weekendRate)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "String learn\&.reservation\&.models\&.Host\&.getAddress ()"

.SS "String learn\&.reservation\&.models\&.Host\&.getCity ()"

.SS "String learn\&.reservation\&.models\&.Host\&.getEmail ()"

.SS "String learn\&.reservation\&.models\&.Host\&.getId ()"

.SS "String learn\&.reservation\&.models\&.Host\&.getLastName ()"

.SS "String learn\&.reservation\&.models\&.Host\&.getPhone ()"

.SS "int learn\&.reservation\&.models\&.Host\&.getPostalCode ()"

.SS "BigDecimal learn\&.reservation\&.models\&.Host\&.getStandardRate ()"

.SS "String learn\&.reservation\&.models\&.Host\&.getState ()"

.SS "BigDecimal learn\&.reservation\&.models\&.Host\&.getWeekendRate ()"

.SS "void learn\&.reservation\&.models\&.Host\&.setAddress (String address)"

.SS "void learn\&.reservation\&.models\&.Host\&.setCity (String city)"

.SS "void learn\&.reservation\&.models\&.Host\&.setEmail (String email)"

.SS "void learn\&.reservation\&.models\&.Host\&.setId (String id)"

.SS "void learn\&.reservation\&.models\&.Host\&.setLastName (String lastName)"

.SS "void learn\&.reservation\&.models\&.Host\&.setPhone (String phone)"

.SS "void learn\&.reservation\&.models\&.Host\&.setPostalCode (int postalCode)"

.SS "void learn\&.reservation\&.models\&.Host\&.setStandardRate (BigDecimal standardRate)"

.SS "void learn\&.reservation\&.models\&.Host\&.setState (String state)"

.SS "void learn\&.reservation\&.models\&.Host\&.setWeekendRate (BigDecimal weekendRate)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
