.TH "learn.reservation.domain.Response" 3 "Mon Apr 19 2021" "Version prj_v1_file" "Mastery Project for Dev10" \" -*- nroff -*-
.ad l
.nh
.SH NAME
learn.reservation.domain.Response
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBlearn\&.reservation\&.domain\&.Result< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBisSuccess\fP ()"
.br
.ti -1c
.RI "List< String > \fBgetErrorMessages\fP ()"
.br
.ti -1c
.RI "void \fBaddErrorMessage\fP (String message)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void learn\&.reservation\&.domain\&.Response\&.addErrorMessage (String message)"

.SS "List<String> learn\&.reservation\&.domain\&.Response\&.getErrorMessages ()"

.SS "boolean learn\&.reservation\&.domain\&.Response\&.isSuccess ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mastery Project for Dev10 from the source code\&.
